// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"
import PreviewsController from "./previews_controller"

application.register("previws", PreviewsController)
// Eager load all data controllers defined in the import map under controllers/**/*_controller
import controllers from "./**/*_controller"
for (const name in controllers) {
  application.register(name, controllers[name])
}

// Lazy load controllers as they appear in the DOM (remember not to preload them in import map!)
// import { eagerLoadControllersFrom } from "@hotwired/stimulus-loading"
// eagerLoadControllersFrom("controllers", application)